/**
 * @description 
 * @author cq
 * @Date 2020-06-08 11:36:50
 * @LastEditTime 2020-06-08 14:25:44
 * @LastEditors cq
 */
/** Declaration file generated by dts-gen */

export = package;



declare module 'dva-loading';


declare module "foo";